name: CI

on:
  pull_request: {}
  push:
    branches:
      - master
      - test

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
        if [ "${{ github.event_name }}" = "push" ]; then
          echo "Hello world"
        else
          echo "Bye world"
        fi
